# Generated by Django 3.0.7 on 2020-08-09 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100, unique=True)),
                ('korisnicko_ime', models.CharField(max_length=20)),
                ('tekst', models.IntegerField(default='Napiši svoju priču!', max_length=1000)),
                ('opis_teksta', models.CharField(default='Pritisnite Naslov Iznad za Detaljniji Pregled Teksta', max_length=300)),
                ('status', models.IntegerField(choices=[(0, 'Nacrt'), (1, 'Objavljeno')], default=0)),
                ('kategorija', models.CharField(default='Izaberite Kategoriju', max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
