# Generated by Django 3.0.7 on 2020-08-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20200809_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='prijava',
            new_name='prijavi',
        ),
    ]
