# Generated by Django 3.0.7 on 2020-08-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200809_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prijavi',
        ),
        migrations.AddField(
            model_name='post',
            name='tuzba',
            field=models.IntegerField(choices=[(0, 'Prijavi'), (1, 'Ne želim')], default=1),
        ),
    ]
