# Generated by Django 3.0.7 on 2020-08-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20200809_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tuzba',
        ),
        migrations.AddField(
            model_name='post',
            name='prijavi',
            field=models.IntegerField(choices=[(0, 'Neću'), (1, 'Hoću')], default=0),
        ),
    ]
