# Generated by Django 3.0.7 on 2020-08-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200809_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prijavi',
        ),
    ]
