# Generated by Django 3.0.7 on 2020-08-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_post_prijavi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prijavi',
            field=models.IntegerField(choices=[(0, 'Ne želim'), (1, 'Želim')], default=0),
        ),
    ]
