# Generated by Django 3.0.7 on 2020-08-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_post_prijavi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prijavi',
            field=models.CharField(default='Prijavi nasilje?', max_length=10),
        ),
    ]
