# Generated by Django 3.0.7 on 2020-08-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200816_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='prijavi',
        ),
    ]
