# Generated by Django 3.0.7 on 2020-08-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_post_prijavi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Objavljeno'), (1, 'Nije objavljeno')], default=1),
        ),
    ]
