# Generated by Django 3.0.7 on 2020-08-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20200816_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='opis_teksta',
            field=models.CharField(default='Dodaj kretak tekst vašoj priči!', max_length=300),
        ),
    ]
