# Generated by Django 3.0.7 on 2020-08-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0016_auto_20200818_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vrijeme',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
