# Generated by Django 3.0.7 on 2020-08-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0017_post_vrijeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='vrijeme',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
