# Generated by Django 3.0.7 on 2020-08-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_prijava'),
    ]

    operations = [
        migrations.AddField(
            model_name='prijava',
            name='tekst',
            field=models.CharField(default='Opišite ukratko Vaš slučaj', max_length=500),
        ),
        migrations.AlterField(
            model_name='prijava',
            name='jedinstveni_maticni_broj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prijava',
            name='starost',
            field=models.IntegerField(),
        ),
    ]
